// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedrequiredannotationtomovieproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrequiredannotationtomovieproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201902261508360_added required annotation to movie properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
